### ISSUE TITLE
Fails with AWS CodeCommit repository URLs

### ISSUE THREAD

**Issue by kodemaniak** [semantic-release/release-notes-generator#182]
The plugin fails if the git repository uses a "non-standard"git URL, e.g., AWS CodeCommit URLs:

```
codecommit::eu-central-1://<profile>@<repository name>
```

I turned link generation of, but the plugin tries to parse the URL anyway:

```
[15:26:27] [semantic-release] » i  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[15:26:27] [semantic-release] » ×  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[15:26:27] [semantic-release] » ×  An error occurred while running semantic-release: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at generateNotes (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\@semantic-release\release-notes-generator\index.js:40:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async validator (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\normalize.js:34:24)
    at async C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\pipeline.js:37:34
    at async C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as generateNotes] (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\index.js:80:11)
    at async run (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\index.js:183:23)
    at async module.exports (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\index.js:260:22)
    at async module.exports (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\cli.js:55:5) {
  pluginName: '@semantic-release/release-notes-generator'
}
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at generateNotes (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\@semantic-release\release-notes-generator\index.js:40:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async validator (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\normalize.js:34:24)
    at async C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\pipeline.js:37:34
    at async C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as generateNotes] (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\lib\plugins\index.js:80:11)
    at async run (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\index.js:183:23)
    at async module.exports (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\index.js:260:22)
    at async module.exports (C:\Users\CASAATHO\Development\aws-ewe-roles\node_modules\semantic-release\cli.js:55:5) {
  pluginName: '@semantic-release/release-notes-generator'
}
```

The fix seems to be to check the result of the match for null and assign the empty array.

**Comment by HaaLeo** [comment]
I run into the exact same error. Why was the PR with the fix closed?

**Comment by leoddias** [comment]
I run into the exact same error. Why was the PR with the fix closed?

**Comment by Roberto-Itauros** [comment]
Same here!

**Comment by vectorstain** [comment]
Testing locally the proposed solution [here](https://github.com/semantic-release/release-notes-generator/pull/183) seams works
