### ISSUE TITLE
An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by Ridermansb** [semantic-release/release-notes-generator#447]
Is throwing an error on Github CI

**Configuration**

```
module.exports = {
  branches: ["master"],
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/exec",
      {
        prepareCmd: "sh ./build.sh v${nextRelease.version}",
        publishCmd: "sh ./publish.sh v${nextRelease.version}",
        successCmd: "sh ./success.sh v${nextRelease.version}"
      }
    ],
    "@semantic-release/github"
  ]
};
```

**packages**
```
"@semantic-release/exec": "^6.0.3",
    "@semantic-release/github": "^8.0.7",
```

**Error**

```
[10:04:17 AM] [semantic-release] › ℹ  Running semantic-release version 21.0.1
[10:04:17 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/node_modules/read-pkg-up/index.js from /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/index.js not supported.
Instead change the require of /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/node_modules/read-pkg-up/index.js in /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/index.js:8:19)
    at async Promise.all (index 0)
    at async loadPlugin (file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/utils.js:60:54)
    at async file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:18:37
    at async file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async default (file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:14:7)
    at async default (file:///home/runner/work/app/app/node_modules/semantic-release/lib/get-config.js:93:30)
    at async Module.default (file:///home/runner/work/app/app/node_modules/semantic-release/index.js:271:34)
    at async default (file:///home/runner/work/app/app/node_modules/semantic-release/cli.js:55:5) ***
  code: 'ERR_REQUIRE_ESM'
***
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/node_modules/read-pkg-up/index.js from /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/index.js not supported.
Instead change the require of /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/node_modules/read-pkg-up/index.js in /home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/index.js:8:19)
    at async Promise.all (index 0)
    at async loadPlugin (file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/utils.js:60:[54](https://github.com/pageHistory/app/actions/runs/4924849880/jobs/8798466610#step:8:55))
    at async file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:18:37
    at async file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async default (file:///home/runner/work/app/app/node_modules/semantic-release/lib/plugins/index.js:14:7)
    at async default (file:///home/runner/work/app/app/node_modules/semantic-release/lib/get-config.js:93:30)
    at async Module.default (file:///home/runner/work/app/app/node_modules/semantic-release/index.js:271:34)
    at async default (file:///home/runner/work/app/app/node_modules/semantic-release/cli.js:55:5) ***
  code: 'ERR_REQUIRE_ESM'
***
```

**Comment by travi** [comment]
what is the output of `npm ls @semantic-release/release-notes-generator` in your project?

**Comment by Ridermansb** [comment]
```
sitehistory@ /Users/ridermansb/Projects/mine/pageHistory/web
└─┬ semantic-release@21.0.2
  └── @semantic-release/release-notes-generator@11.0.1

```

**Comment by Ridermansb** [comment]
![image](https://github.com/semantic-release/release-notes-generator/assets/725337/812d4d70-b242-4cd9-a968-463f15bef234)

**Comment by travi** [comment]
i'm trying to make sense of this error. the version of release-notes-generator that you have in your project is esm-only and does not use require, so i dont understand what could be happening. is some sort of transpilation happening in your project that could be modifying `/home/runner/work/app/app/node_modules/@semantic-release/release-notes-generator/index.js`? could you open that file and confirm if it contains `require` at the time that your release happens?

**Comment by devRabbani** [comment]
@Ridermansb  what happen to this issue? I am also having same issue

**Comment by vvanouytsel** [comment]
@Ridermansb it would be helpful to state why you closed this as completed indeed.

**Comment by ben741** [comment]
I'm also running into this issue in Github Actions. Does anyone know what the cause is and how to resolve it?

Edit: upon closer inspection, my issue was different, occurring in semantic-release/commit-analyzer: 
```
[6:03:43 PM] [semantic-release] › ✘  Failed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:03:43 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module ....
```

And pinning it to some earlier version helped:
```
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits@6.1.0
```

**Comment by nbcchen** [comment]
I have the same issue. The project type is `module`. What should I do?
