### ISSUE TITLE
semantic-release fails at `release-notes-generator` step

### ISSUE THREAD

**Issue by tarunfeb27** [semantic-release/release-notes-generator#662]
Hello,

I am having a problem with `semantic-release` command, release workflow fails at step "`generateNotes`" of plugin "`@semantic-release/release-notes-generator`"

I am using latest versions of packages 
```
├─┬ @semantic-release/changelog@6.0.3
│ └─┬ semantic-release@24.0.0
│   ├─┬ @semantic-release/github@10.0.6
│   │ └── semantic-release@24.0.0 deduped
│   └─┬ @semantic-release/npm@12.0.1
│     └── semantic-release@24.0.0 deduped
├─┬ @semantic-release/commit-analyzer@13.0.0
│ └── semantic-release@24.0.0 deduped
├─┬ @semantic-release/exec@6.0.3
│ └── semantic-release@24.0.0 deduped
├─┬ @semantic-release/git@10.0.1
│ └── semantic-release@24.0.0 deduped
└─┬ @semantic-release/release-notes-generator@14.0.0
  └── semantic-release@24.0.0 deduped
az-tf-module-aks@ /home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks
└── conventional-changelog-conventionalcommits@8.0.0
[9:01:20 AM] [semantic-release] › ℹ  Running semantic-release version 24.0.0
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[9:01:20 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[9:01:21 AM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/DevopsDiver/az-tf-module-aks
[9:01:21 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:01:21 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[9:01:21 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[9:01:21 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[9:01:21 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[9:01:21 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[9:01:21 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[9:01:21 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[9:01:21 AM] [semantic-release] › ℹ  Found git tag v0.1.0 associated with version 0.1.0 on branch main
[9:01:21 AM] [semantic-release] › ℹ  Found 10 commits since last release
[9:01:21 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[9:01:21 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #3 from DevopsDiver/fix/semantic-release
fix: Issues with semantic-release workflow, debug using this PR
[9:01:21 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[9:01:21 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat!: breaking change feature - debug release
[9:01:21 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major
[9:01:21 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 10 commits complete: major release
[9:01:21 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[9:01:21 AM] [semantic-release] › ℹ  The next release version is 1.0.0
[9:01:21 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:01:21 AM] [semantic-release] › ✘  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:01:21 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: Cannot read properties of null (reading 'match')
    at addBangNotes (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-conventionalcommits/src/utils.js:5:31)
    at transform (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-conventionalcommits/src/writer.js:81:19)
    at transformCommit (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-writer/dist/commit.js:29:23)
    at write (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-writer/dist/writers.js:39:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async next (node:internal/streams/from:85:11) {
  pluginName: '@semantic-release/release-notes-generator'
}
TypeError: Cannot read properties of null (reading 'match')
    at addBangNotes (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-conventionalcommits/src/utils.js:5:31)
    at transform (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-conventionalcommits/src/writer.js:81:19)
    at transformCommit (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-writer/dist/commit.js:29:23)
    at write (file:///home/runner/work/az-tf-module-aks/az-tf-module-aks/home/runner/work/az-tf-module-aks/az-tf-module-aks/node_modules/conventional-changelog-writer/dist/writers.js:39:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async next (node:internal/streams/from:85:11) {
  pluginName: '@semantic-release/release-notes-generator'
}
Error: Process completed with exit code 1.
```

Strangly stopped working since last night, same config worked well previously. I am not pinning the versions of plugins and they are being installed latest. 
 Had some changes in past due to issue https://github.com/semantic-release/release-notes-generator/issues/633, but looks like this is unrelated. 

Update: This could some local issue in my set up, still unable to find root cause. I am using reusable workflow for semantic release from all my repos and some of them are working fine, set up wise everything is identical. I might be missing very small detail somewhere. :(

**Comment by tarunfeb27** [comment]
This has been very strange issue, create a copy of existing repo and pushed to GH as a new repo from scratch and tried to reproduce. Could not. 
Looks like one bad commit (merge from main to feature) caused this. I created a manual release. Then subsequent ones are working fine.
