### ISSUE TITLE
 Cannot modify immutable object

### ISSUE THREAD

**Issue by Admirari80** [semantic-release/release-notes-generator#685]
```
[9:44:39 AM] [semantic-release] › ℹ  Running semantic-release version 24.0.0
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
[9:44:39 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
[9:44:40 AM] [semantic-release] › ✔  Run automated release from branch main on repository git@gitlab.aprixon.de:base/core/images/semantic-release.git
[9:44:40 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:44:40 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[9:44:40 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[9:44:40 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[9:44:40 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[9:44:40 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[9:44:40 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.aprixon.de/api/v4)
[9:44:40 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[9:44:40 AM] [semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1 on branch main
[9:44:40 AM] [semantic-release] › ℹ  Found 6 commits since last release
[9:44:40 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge branch 'update_yarn_lock' into 'main'
refactor: update yarn.lock
See merge request base/core/images/semantic-release!11
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: change yarn.lock
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: refactor: .gitlab-ci.yml
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge branch 'main' of gitlab.aprixon.de:base/core/images/semantic-release
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(deps): update dependency @semantic-release/gitlab to v13.2.0
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: set branch in base.config.js as master
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[9:44:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 6 commits complete: patch release
[9:44:40 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[9:44:40 AM] [semantic-release] › ℹ  The next release version is 1.0.2
[9:44:40 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:44:40 AM] [semantic-release] › ✘  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:44:40 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot modify immutable object.
    at Object.set (file:///node_modules/conventional-changelog-writer/dist/commit.js:11:19)
    at transform (/opt/base.config.js:41:21)
    at transformCommit (file:///node_modules/conventional-changelog-writer/dist/commit.js:29:23)
    at write (file:///node_modules/conventional-changelog-writer/dist/writers.js:39:[28](https://gitlab.aprixon.de/base/core/images/semantic-release/-/jobs/212579#L28))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async nextAsync (node:internal/streams/from:182:33) {
  pluginName: '@semantic-release/release-notes-generator'
}
Error: Cannot modify immutable object.
    at Object.set (file:///node_modules/conventional-changelog-writer/dist/commit.js:11:19)
    at transform (/opt/base.config.js:41:21)
    at transformCommit (file:///node_modules/conventional-changelog-writer/dist/commit.js:[29](https://gitlab.aprixon.de/base/core/images/semantic-release/-/jobs/212579#L29):23)
    at write (file:///node_modules/conventional-changelog-writer/dist/writers.js:39:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async nextAsync (node:internal/streams/from:182:33) {
  pluginName: '@semantic-release/release-notes-generator'
}
```

```
# base.config.js
const commitAnalyzerOptions = {
  preset: "angular",
  releaseRules: [
    { type: "docs", release: false },
    { type: "refactor", release: "patch" },
    { type: "chore", release: "patch" }
  ]
};

const releaseNotesGeneratorOptions = {
  parserOpts: {
    headerPattern: /^(\w*)(?:\((.*)\))?: (.*)$/,
    headerCorrespondence: ["type", "scope", "subject"],
    noteKeywords: ["BREAKING CHANGE"],
    revertPattern: /^(?:Revert|revert:)\s"?([\s\S]+?)"?\s*This reverts commit (\w*)\./i,
    revertCorrespondence: ["header", "hash"]
  },
  writerOpts: {
    transform: (commit, context) => {
      let discard = true;
      const issues = [];

      commit.notes.forEach((note) => {
        note.title = "BREAKING CHANGES";
        discard = false;
      });

      if (commit.type === "feat") {
        commit.type = "Features";
      } else if (commit.type === "fix") {
        commit.type = "Bug Fixes";
      } else if (commit.type === "perf") {
        commit.type = "Performance Improvements";
      } else if (commit.type === "revert" || commit.revert) {
        commit.type = "Reverts";
      } else if (commit.type === "docs") {
        commit.type = "Documentation";
      } else if (commit.type === "style") {
        commit.type = "Styles";
      } else if (commit.type === "refactor") {
        commit.type = "Code Refactoring";
      } else if (commit.type === "chore") {
        commit.type = "Miscellaneous Chores";
      } else if (commit.type === "test") {
        commit.type = "Tests";
      } else if (commit.type === "build") {
        commit.type = "Build System";
      } else if (commit.type === "ci") {
        commit.type = "Continuous Integration";
      } else {
        return;
      }

      if (commit.scope === "*") {
        commit.scope = "";
      }

      if (typeof commit.hash === "string") {
        commit.shortHash = commit.hash.substring(0, 7);
      }

      if (typeof commit.subject === "string") {
        const base_url = "https://xxxxxxxxx.atlassian.net/browse/";
        if (base_url) {
          // Issue URLs for jira tickets
          commit.subject = commit.subject.replace(
            /[LWK|DEVOPS|MMA|WSCS|TJ|TT|GPS|WM|WSP]+-[0-9]+/g,
            (issue, idx) => {
              issues.push(idx);
              return `[${issue}](${base_url}${issue})`;
            }
          );
        }
      }

      // remove references that already appear in the subject
      commit.references = commit.references.filter((reference) => {
        if (issues.indexOf(reference.issue) === -1) {
          return true;
        }

        return false;
      });

      // DO NOT REMOVE
      return commit;
    },
  },
};

module.exports = {
  debug: true,
  plugins: [
    ["@semantic-release/commit-analyzer", commitAnalyzerOptions],
    ["@semantic-release/release-notes-generator", releaseNotesGeneratorOptions],
    [
      "@semantic-release/changelog",
      {
        changelogFile: "CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/git",
      {
        assets: ["CHANGELOG.md"]
      }
    ],
    "@semantic-release/gitlab"
  ],
  branches: ["master"]
};
```

```
{
# package.json
  "name": "semantic-release",
  "version": "1.0.0",
  "description": "basic image with semantic-release and some plugins",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git@xxxxxxxxxxxxxxxxxxxxxx/semantic-release.git"
  },
  "author": "xxxxxx",
  "dependencies": {
    "semantic-release-replace-plugin": "1.2.7",
    "@semantic-release/changelog": "6.0.3",
    "@semantic-release/commit-analyzer": "13.0.0",
    "@semantic-release/git": "10.0.1",
    "@semantic-release/gitlab": "13.2.0",
    "@semantic-release/npm": "12.0.1",
    "@semantic-release/release-notes-generator": "14.0.1",
    "semantic-release": "24.0.0"
  }
}
```

Unfortunately, semantic release fails without custom modifications. Does anyone know the reason for "Error: Cannot modify immutable object or can give me a hint, please."

**Comment by secondmanveran** [comment]
👍🏻 

I'm having the same issue using this stack of plugins:

```json
"devDependencies": {
  "@commitlint/cli": "^19.3.0",
  "@commitlint/config-conventional": "^19.2.2",
  "@semantic-release/changelog": "^6.0.3",
  "@semantic-release/git": "^10.0.1",
  "@semantic-release/gitlab": "^13.2.0",
  "semantic-release": "^24.0.0"
}
```

This stack works:

```json
"devDependencies": {
  "@commitlint/cli": "^19.2.0",
  "@commitlint/config-conventional": "^19.1.0",
  "@semantic-release/changelog": "^6.0.3",
  "@semantic-release/git": "^10.0.1",
  "@semantic-release/gitlab": "^13.0.3",
  "semantic-release": "^23.0.3"
}
```

I'll switch back for the moment, but wanted to chime in that this is definitely a bug.

**Comment by Admirari80** [comment]
> 👍🏻
> 
> I'm having the same issue using this stack of plugins:
> 
> ```json
> "devDependencies": {
>   "@commitlint/cli": "^19.3.0",
>   "@commitlint/config-conventional": "^19.2.2",
>   "@semantic-release/changelog": "^6.0.3",
>   "@semantic-release/git": "^10.0.1",
>   "@semantic-release/gitlab": "^13.2.0",
>   "semantic-release": "^24.0.0"
> }
> ```
> 
> This stack works:
> 
> ```json
> "devDependencies": {
>   "@commitlint/cli": "^19.2.0",
>   "@commitlint/config-conventional": "^19.1.0",
>   "@semantic-release/changelog": "^6.0.3",
>   "@semantic-release/git": "^10.0.1",
>   "@semantic-release/gitlab": "^13.0.3",
>   "semantic-release": "^23.0.3"
> }
> ```
> 
> I'll switch back for the moment, but wanted to chime in that this is definitely a bug.

My problem still remains with the versions you mentioned.

**Comment by Admirari80** [comment]
I suspect that the cause lies somewhere in our self-hosted GitLab. Does anyone have any ideas/approaches?

**Comment by secondmanveran** [comment]
@Admirari80 

This issue is in the actual semantic-release package. I left everything else to latest and switched it back to 23.0.3 and the issue is resolved.

**Comment by travi** [comment]
what does `npm ls conventional-changelog-writer` give you? i suspect there is likely a version conflict between semantic-release and your use of `@commitlint/config-conventional`

**Comment by Admirari80** [comment]
> what does `npm ls conventional-changelog-writer` give you? i suspect there is likely a version conflict between semantic-release and your use of `@commitlint/config-conventional`

```
$ npm ls conventional-changelog-writer
/
+-- @semantic-release/commit-analyzer@13.0.0 extraneous
| `-- conventional-changelog-writer@8.0.0 deduped
+-- @semantic-release/release-notes-generator@14.0.1 extraneous
| `-- conventional-changelog-writer@8.0.0 deduped
+-- conventional-changelog-writer@8.0.0 extraneous
`-- semantic-release@24.0.0 extraneous
  `-- @semantic-release/release-notes-generator@14.0.0 extraneous
    `-- conventional-changelog-writer@8.0.0 deduped
```

**Comment by Admirari80** [comment]
> what does `npm ls conventional-changelog-writer` give you? i suspect there is likely a version conflict between semantic-release and your use of `@commitlint/config-conventional`

why does it work at gitlab.com and not at our company gitlab?

**Comment by Admirari80** [comment]
another approach was to compare both Dockerimages, one which is still working and the failing one. There is the diff of folders in the node_modules, but I don't know why this happens. The Dockerfile is the same one...

0.0.1 is the working one

```
Only in 0-0-1/node_modules/.bin: JSONStream
Only in 0-0-1/node_modules/@babel/code-frame/lib: index.js.map
Only in 0-0-1/node_modules/@babel/helper-validator-identifier/lib: identifier.js.map
Only in 0-0-1/node_modules/@babel/helper-validator-identifier/lib: index.js.map
Only in 0-0-1/node_modules/@babel/helper-validator-identifier/lib: keyword.js.map
Only in 0-0-1/node_modules/@babel/highlight/lib: index.js.map
Only in 0-0-1/node_modules/@semantic-release/release-notes-generator/node_modules: conventional-changelog-angular
Only in 0-0-1/node_modules/@semantic-release/release-notes-generator/node_modules: conventional-changelog-writer
Only in 0-0-1/node_modules/@semantic-release/release-notes-generator/node_modules: conventional-commits-filter
Only in 0-0-1/node_modules/@semantic-release/release-notes-generator/node_modules: conventional-commits-parser
Only in 0-0-1/node_modules/@semantic-release/release-notes-generator/node_modules: lru-cache
Only in 0-0-1/node_modules/@semantic-release/release-notes-generator/node_modules: semver
Only in 0-0-1/node_modules/conventional-changelog-writer/node_modules: meow
Only in 0-0-1/node_modules/conventional-commits-parser: node_modules
Only in 0-0-1/node_modules/cosmiconfig/node_modules: @babel
Only in 0-0-1/node_modules/cosmiconfig/node_modules: json-parse-even-better-errors
Only in 0-0-1/node_modules/cosmiconfig/node_modules: parse-json
Only in 0-0-1/node_modules/find-up: index.d.ts
Only in 0-0-1/node_modules/git-log-parser: node_modules
Only in 0-0-1/node_modules/locate-path: index.d.ts
Only in 0-0-1/node_modules/p-limit: index.d.ts
Only in 0-0-1/node_modules/p-locate: index.d.ts
Only in 0-0-1/node_modules/parse-json: index.d.ts
Only in 0-0-1/node_modules/path-exists: index.d.ts
Only in 0-0-1/node_modules/pkg-conf: node_modules
Only in 0-0-1/node_modules/read-pkg-up: node_modules
Only in 0-0-1/node_modules/semantic-release/node_modules: read-pkg-up
Only in 0-0-1/node_modules/split2: bench.js
Only in 0-0-1/node_modules: JSONStream
Only in 0-0-1/node_modules: import-from
Only in 0-0-1/node_modules: is-text-path
Only in 0-0-1/node_modules: json-stringify-safe
Only in 0-0-1/node_modules: picocolors
Only in 0-0-1/node_modules: text-extensions
Only in 0-0-1/node_modules: through
Only in 0-0-1/node_modules: yocto-queue
Only in 2-0-1/node_modules/parse-json: node_modules
Only in 2-0-1/node_modules/read-pkg: node_modules
Only in 2-0-1/node_modules/split2: .npmignore
Only in 2-0-1/node_modules/split2: .travis.yml
```

**Comment by Admirari80** [comment]
I have no idea where the differences are coming from, but the answer should be the solution to my problem.

[diff in files.txt](https://github.com/user-attachments/files/16286304/diff.in.files.txt)


@travi, any suggestions?

**Comment by Admirari80** [comment]
@travi and @secondmanveran: I fixed the issue.

I have identified my problem. After upgrading to semantic-release/release-notes-generator@14.0.0, some dependencies are missing. Take a look at my screenshot.

![diff](https://github.com/user-attachments/assets/1695372a-c242-4dbe-b9ad-55095467626c)

**Comment by travi** [comment]
Could you clarify what actions you took to resolve the problem in case others run into similar?

**Comment by travi** [comment]
Ah, I didn't catch this before, but why are you/we're you depending on the release-notes-generator directly. Since semantic-release depends on it already, there should be no need and can result in conflicts.

**Comment by Admirari80** [comment]
> Ah, I didn't catch this before, but why are you/we're you depending on the release-notes-generator directly. Since semantic-release depends on it already, there should be no need and can result in conflicts.

I also don't understand why it works on one system and not on the other.

**Comment by travi** [comment]
sorry for the delayed follow up. i was traveling, so i've fallen even further behind here. it appears that the issue came about because of conflicting versions of dependencies. as mentioned above, you were capturing release-notes-generator, for example, as a direct dependency when semantic-release already depends on it. then an upgrade on the semantic-release side resulted in two different versions being pulled into your project.

there should be no reason for you to directly depend on any of the packages that semantic-release already depends on. please look through your dependencies and remove any that are already pulled in by semantic-release. `npm ls <package-name>` can be helpful to determine this.

as for the difference between systems, it is likely a difference in how your dependency tree is built between those systems. in the failing case, the dependency tree was invalid, likely because of the conflicts i mentioned. installing from a lockfile can help with this, or installing latest as part of executing with npx

**Comment by Admirari80** [comment]
@travi, hhank you very much for the detailed description.
